pipeline{
    
    agent { label "chawaa" };
    
    stages{
        stage("code clone"){
            steps{
                git url: "https://github.com/AWS-DevOps-shubh/online_shop.git", branch: "feature/feature-shubham-tayde"
            }
        }
    stage("code build"){
        steps{
            sh "docker build -t online-shop ."
        }   
    } 
    stage("test code"){
        steps{
            echo "test code succefully"
            
        }
    }
    stage("code deploy"){
        steps{
            sh "docker run -d -p 5000:5000 --name online-shop12 online-shop:latest123"
        }
    }
    
    } 
}
